name: audit

defaults:
  run:
    shell: pwsh

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight.

jobs:
  audit:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Security audit
      uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
